docker_repo: docker-ce.repo

#USER
docker_user: qmtmabbu

#WEB
web_docker_img_name: web
web_docker_img_tag: latest
web_container_name: webserver
web_ports: 81:81
web_dockerfile_path: docker/web/

#DB
db_docker_img_name: db
db_docker_img_tag: latest
db_container_name: dbserver
db_ports: 3308:3308
db_dockerfile_path: docker/db/
