---
# tasks file for dockerfile

- name: Build Web server Docker image
  docker_image:
    name: "{{ web_docker_img_name }}"
    build:
      path: "{{ web_dockerfile_path }}"
      pull: no
    state: present
    source: build
  register: web_docker_img

- name: Build DB server Docker image
  docker_image:
    name: "{{ db_docker_img_name }}"
    build:
      path: "{{ db_dockerfile_path }}"
      pull: no
    state: present
    source: build
  register: db_docker_img

- name: Clear IPTables filter
  shell: iptables -F; iptables -X

- name: Restart Docker
  service:
    name: docker
    state: restarted

# tasks file for run docker container
- name: Run Web server container
  docker_container:
    name: "{{ web_container_name }}"
    image: "{{ web_docker_img_name }}:{{ web_docker_img_tag }}"
    privileged: yes
    published_ports: "{{ web_ports }}"

- name: Run DB server container
  docker_container:
    name: "{{ db_container_name }}"
    image: "{{ db_docker_img_name }}:{{ db_docker_img_tag }}"
    privileged: yes
    published_ports: "{{ db_ports }}"
